language: go
go:
 - 1.2
 - 1.3
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - 1.8
install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls
 - go get -v ./related
script:
 - go test -v ./related -covermode=count -coverprofile=coverage.out
 - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

